### ISSUE TITLE
fdPrivateMail is already in personal tab

### ISSUE THREAD

**Issue by MCMic** [tiredofit/fusiondirectory-plugin-kopano#2]
fdPrivateMail is already in personal plugin tab so you should not add it in another tab.

Attributes need to be unique across tabs.

**Comment by tiredofit** [comment]
Thanks for the tip. I am pretty new to plugin building here, and working just off our existing attributes as I try to unpack how to make this work properly. I do realize I should be following a similar path to the Posix Plugin so that it's an entirely separate object class with it's own unique attributes. I plan on rearranging it once I figure out how to make it work for Groups as well.

**Comment by tiredofit** [comment]
Removed
